# Generated by Django 5.2.5 on 2025-08-30 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_movimentacaocaixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='metodo_pagamento',
            field=models.CharField(blank=True, choices=[('cartao de credito', 'Cartão de crédito'), ('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('caderno', 'Caderno')], max_length=50, null=True),
        ),
    ]
