# Generated by Django 5.2.5 on 2025-08-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_lancamento_metodo_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaocaixa',
            name='tipo_movimentacao',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('transferencia_cofrinho', 'Transferência para Cofrinho'), ('injetar_dinheiro', 'Injeção de Dinheiro'), ('resgate_cofrinho', 'Resgate de Cofrinho')], max_length=50),
        ),
    ]
