# Generated by Django 5.2.5 on 2025-08-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_movimentacaocaixa_tipo_movimentacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lancamento',
            name='metodo_pagamento',
        ),
        migrations.AlterField(
            model_name='movimentacaocaixa',
            name='tipo_movimentacao',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('transferencia_cofrinho', 'Transferência para Cofrinho'), ('injetar_dinheiro', 'Injeção de Dinheiro')], max_length=50),
        ),
    ]
