# Generated by Django 5.2.5 on 2025-09-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_metodopagamento_lancamento_metodo_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodopagamento',
            name='nome',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('cartao_credito', 'Cartão de Crédito'), ('caderno', 'Caderno')], max_length=100, unique=True),
        ),
    ]
