# Generated by Django 5.2.5 on 2025-09-01 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_metodopagamento_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='metodo_pagamento',
            field=models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('caderno', 'Caderno')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacaocaixa',
            name='tipo_movimentacao',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('transferencia_cofrinho', 'Transferência para Cofrinho'), ('injetar_dinheiro', 'Injeção de Dinheiro'), ('quitacao_divida', 'Quitação de Dívida')], max_length=50),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='devedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='home.devedor'),
        ),
        migrations.CreateModel(
            name='Divida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_criacao', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('quitada', models.BooleanField(default=False)),
                ('devedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividas', to='home.devedor')),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividas', to='home.lancamento')),
            ],
        ),
        migrations.DeleteModel(
            name='MetodoPagamento',
        ),
    ]
