# Generated by Django 5.2.5 on 2025-09-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_devedor_alter_lancamento_metodo_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devedor',
            name='contato',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
