# Generated by Django 5.2.5 on 2025-09-03 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_devedor_contato'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Caixa',
        ),
        migrations.RemoveField(
            model_name='divida',
            name='devedor',
        ),
        migrations.RemoveField(
            model_name='lancamento',
            name='devedor',
        ),
        migrations.RemoveField(
            model_name='divida',
            name='lancamento',
        ),
        migrations.DeleteModel(
            name='MovimentacaoCaixa',
        ),
        migrations.DeleteModel(
            name='Devedor',
        ),
        migrations.DeleteModel(
            name='Divida',
        ),
    ]
