# Generated by Django 5.2.5 on 2025-09-03 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_delete_caixa_remove_divida_devedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='cofrinho_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias', to='home.cofrinho'),
        ),
    ]
