# Generated by Django 5.2.5 on 2025-09-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_lancamento_cofrinho_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='cofrinho',
            name='meta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
