# Generated by Django 5.2.5 on 2025-09-05 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_cofrinho_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do cartão (ex: Nubank, Itaú, etc)', max_length=100)),
                ('limite_total', models.DecimalField(decimal_places=2, help_text='Limite total do cartão', max_digits=10)),
                ('limite_disponivel', models.DecimalField(decimal_places=2, help_text='Limite disponível atual', max_digits=10)),
                ('dia_vencimento', models.IntegerField(help_text='Dia do vencimento da fatura (1-31)')),
                ('dia_fechamento', models.IntegerField(help_text='Dia do fechamento da fatura (1-31)')),
                ('ativo', models.BooleanField(default=True, help_text='Se o cartão está ativo para uso')),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cartão de Crédito',
                'verbose_name_plural': 'Cartões de Crédito',
            },
        ),
        migrations.AddField(
            model_name='lancamento',
            name='cartao_credito',
            field=models.ForeignKey(blank=True, help_text='Cartão utilizado (obrigatório quando método de pagamento for cartão de crédito)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='home.cartaocredito'),
        ),
    ]
